---
 - name: install apache & php for ubuntu servers
   tags: apache2-ubuntu
   apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest
     update_cache: yes
   when: ansible_distribution == "Ubuntu"

 - name: install apache & php for centos servers
   tags: centos-httpd
   dnf:
     name:
       - httpd
       - php
     state: latest
   when: ansible_distribution == "CentOS"

 - name: start httpd for centOS
   tags: centos-httpd
   service:
     name: httpd
     state: started
     enabled: true
   when: ansible_distribution == "CentOS"
